version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=email@provider.com     # Required
      - "PASS=P@SSW0RD"         # Required
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.255.0/24  # So it can be accessed within the local network. Enter your own here
      - CONNECT=United_States    # Or anywhere else for that matter. Can also be left out. Optional
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
